In [114]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time
import random
import math
from datetime import datetime, timedelta
import numpy as np
from itertools import combinations
import string

In [2]:
def get_companies(urls_paises = {
    "France": [
        "https://disfold.com/france/companies/?page=1",
        "https://disfold.com/france/companies/?page=2",
        "https://disfold.com/france/companies/?page=3",
        "https://disfold.com/france/companies/?page=4"
    ],
    "Germany": [
        "https://disfold.com/germany/companies/?page=1",
        "https://disfold.com/germany/companies/?page=2",
        "https://disfold.com/germany/companies/?page=3",
        "https://disfold.com/germany/companies/?page=4"
    ],
    "United-Kingdom": [
        "https://disfold.com/united-kingdom/companies/?page=1",
        "https://disfold.com/united-kingdom/companies/?page=2",
        "https://disfold.com/united-kingdom/companies/?page=3",
        "https://disfold.com/united-kingdom/companies/?page=4"
    ],
    "Spain": [
        "https://disfold.com/spain/companies/?page=1",
        "https://disfold.com/spain/companies/?page=2",
        "https://disfold.com/spain/companies/?page=3",
        "https://disfold.com/spain/companies/?page=4"
    ],
    "Italy": [
        "https://disfold.com/italy/companies/?page=1",
        "https://disfold.com/italy/companies/?page=2",
        "https://disfold.com/italy/companies/?page=3",
        "https://disfold.com/italy/companies/?page=4"
    ],
    "Ireland": [
        "https://disfold.com/ireland/companies/?page=1",
        "https://disfold.com/ireland/companies/?page=2"
    ]
} ):
    nombres_empresas = []
    paises_empresas = []

    for pais, urls in urls_paises.items():
        for url in urls:
            response = requests.get(url)
            soup = BeautifulSoup(response.text, 'html.parser')
            table = soup.find('table', {'class': 'striped'})
            rows = table.find_all('tr')

            for row in rows:
                cols = row.find_all('td')
                if len(cols) >= 2:
                    nombres_empresas.append(cols[1].get_text().strip())
                    paises_empresas.append(pais)
            
            time.sleep(1)  # Espera 1 segundo entre solicitudes

    return (nombres_empresas, paises_empresas)

In [3]:
# companies = get_companies()

In [4]:
def comp_name(quantity, countries=None):
    # Si no se especifican países, se utilizan estos por defecto
    if countries is None:
        countries = ["Spain", "Italy", "Germany", "United-Kingdom", "Ireland", "France"]

    # Asumiendo que 'companies' es una tupla (lista_empresas, lista_paises)
    lista_empresas, lista_paises = companies

    # Filtrar las empresas por los países especificados
    empresas_filtradas = [(lista_empresas[i], lista_paises[i]) for i in range(len(lista_empresas)) if lista_paises[i] in countries]

    # Asegurarse de que la cantidad solicitada no sea mayor que la cantidad disponible
    quantity = min(quantity, len(empresas_filtradas))

    # Seleccionar aleatoriamente una cantidad determinada de empresas
    empresas_seleccionadas = random.sample(empresas_filtradas, quantity)

    # Crear y devolver un diccionario con los nombres de las empresas y sus países
    resultado = {nombre: pais for nombre, pais in empresas_seleccionadas}

    return resultado

In [5]:
# comp_name(1058)

In [6]:
name_comp = pd.read_csv('companies.csv', encoding = 'utf-8', delimiter=';')
name_comp.head()
# name_comp['country'].unique()

                             company_name country
0  LVMH Moët Hennessy - Louis Vuitton, SE  France
1                              L'Oréal SA  France
2                Hermès International SCA  France
3                       Christian Dior SE  France
4                        TotalEnergies SE  France

In [7]:
# # Asumiendo que companies es una tupla de dos listas (lista_empresas, lista_paises)
# lista_empresas, lista_paises = companies

# # Crear un DataFrame a partir de la tupla
# df = pd.DataFrame({
#     'company_name': lista_empresas,
#     'country': lista_paises
# })

# # Guardar el DataFrame en un archivo CSV, separado por ';'
# df.to_csv('companies.csv', sep=';', index=False, encoding='utf-8')

In [8]:
cities = {
    "Jerez de la Frontera": "Spain", "Madrid": "Spain", "Barcelona": "Spain",
    "Seville": "Spain", "Valencia": "Spain", "Bilbao": "Spain",
    "Malaga": "Spain", "Zaragoza": "Spain", "Murcia": "Spain", "Palma": "Spain",
    "Paris": "France", "Marseille": "France", "Lyon": "France",
    "Toulouse": "France", "Nice": "France", "Nantes": "France",
    "Strasbourg": "France", "Montpellier": "France", "Bordeaux": "France", "Lille": "France",
    "London": "United Kingdom", "Manchester": "United Kingdom", "Liverpool": "United Kingdom",
    "Edinburgh": "United Kingdom", "Glasgow": "United Kingdom", "Birmingham": "United Kingdom",
    "Leeds": "United Kingdom", "Bristol": "United Kingdom", "Sheffield": "United Kingdom", "Leicester": "United Kingdom",
    "Berlin": "Germany", "Munich": "Germany", "Frankfurt": "Germany",
    "Hamburg": "Germany", "Cologne": "Germany", "Stuttgart": "Germany",
    "Düsseldorf": "Germany", "Dortmund": "Germany", "Essen": "Germany", "Leipzig": "Germany",
    "Rome": "Italy", "Milan": "Italy", "Naples": "Italy",
    "Turin": "Italy", "Palermo": "Italy", "Genoa": "Italy",
    "Bologna": "Italy", "Florence": "Italy", "Bari": "Italy", "Catania": "Italy",
    "Dublin": "Ireland", "Cork": "Ireland", "Limerick": "Ireland",
    "Galway": "Ireland", "Waterford": "Ireland"
}

In [9]:
addresses = {}

# Ciudades en España
spain_cities = [
    "Jerez de la Frontera", "Madrid", "Barcelona", "Seville", "Valencia", "Bilbao",
    "Malaga", "Zaragoza", "Murcia", "Palma"
]

# Ciudades en Francia
france_cities = [
    "Paris", "Marseille", "Lyon", "Toulouse", "Nice", "Nantes",
    "Strasbourg", "Montpellier", "Bordeaux", "Lille"
]

# Ciudades en Reino Unido
uk_cities = [
    "London", "Manchester", "Liverpool", "Edinburgh", "Glasgow", "Birmingham",
    "Leeds", "Bristol", "Sheffield", "Leicester"
]

# Ciudades en Alemania
germany_cities = [
    "Berlin", "Munich", "Frankfurt", "Hamburg", "Cologne", "Stuttgart",
    "Düsseldorf", "Dortmund", "Essen", "Leipzig"
]

# Ciudades en Italia
italy_cities = [
    "Rome", "Milan", "Naples", "Turin", "Palermo", "Genoa",
    "Bologna", "Florence", "Bari", "Catania"
]

# Ciudades en Irlanda
ireland_cities = [
    "Dublin", "Cork", "Limerick", "Galway", "Waterford"
]

# Calles famosas por ciudad
streets_by_city = {
    "Jerez de la Frontera": ["Calle Larga", "Avenida Alcalde Álvaro Domecq", "Calle Sevilla"],
    "Madrid": ["Gran Vía", "Calle Mayor", "Paseo de la Castellana"],
    "Barcelona": ["La Rambla", "Passeig de Gràcia", "Avinguda Diagonal"],
    "Seville": ["Calle Sierpes", "Avenida de la Constitución", "Paseo de Colón"],
    "Valencia": ["Carrer de Colón", "Carrer de Xàtiva", "Carrer de la Pau"],
    "Bilbao": ["Gran Vía", "Calle Licenciado Poza", "Calle Ercilla"],
    "Malaga": ["Calle Marqués de Larios", "Calle Granada", "Calle Alcazabilla"],
    "Zaragoza": ["Paseo de la Independencia", "Calle Don Jaime I", "Calle Alfonso I"],
    "Murcia": ["Gran Vía Escultor Francisco Salzillo", "Avenida Teniente Flomesta", "Calle Trapería"],
    "Palma": ["Passeig des Born", "Carrer de Sant Miquel", "Plaça Major"],
    "Paris": ["Champs-Élysées", "Avenue de l'Opéra", "Rue de Rivoli"],
    "Marseille": ["Rue de la République", "Canebière", "Rue Saint-Ferréol"],
    "Lyon": ["Rue de la République", "Place Bellecour", "Rue Victor Hugo"],
    "Toulouse": ["Place du Capitole", "Allées Jean-Jaurès", "Rue de Metz"],
    "Nice": ["Promenade des Anglais", "Avenue Jean Médecin", "Place Masséna"],
    "Nantes": ["Rue du Calvaire", "Place Royale", "Rue Crébillon"],
    "Strasbourg": ["Place Kléber", "Rue du 22 Novembre", "Rue des Grandes Arcades"],
    "Montpellier": ["Place de la Comédie", "Rue de la Loge", "Rue Saint-Guilhem"],
    "Bordeaux": ["Rue Sainte-Catherine", "Place de la Bourse", "Quai des Chartrons"],
    "Lille": ["Grand'Place", "Rue de la Monnaie", "Rue Esquermoise"],
    "London": ["Oxford Street", "Regent Street", "Baker Street"],
    "Manchester": ["Deansgate", "Market Street", "King Street"],
    "Liverpool": ["Mathew Street", "Bold Street", "Castle Street"],
    "Edinburgh": ["Royal Mile", "Princes Street", "George Street"],
    "Glasgow": ["Buchanan Street", "Argyle Street", "Sauchiehall Street"],
    "Birmingham": ["Bullring", "New Street", "Broad Street"],
    "Leeds": ["Briggate", "Albion Street", "Boar Lane"],
    "Bristol": ["Park Street", "Baldwin Street", "Queen Square"],
    "Sheffield": ["Fargate", "Division Street", "Ecclesall Road"],
    "Leicester": ["High Street", "Granby Street", "Belvoir Street"],
    "Berlin": ["Unter den Linden", "Kurfürstendamm", "Friedrichstraße"],
    "Munich": ["Marienplatz", "Kaufingerstraße", "Maximilianstraße"],
    "Frankfurt": ["Zeil", "Schillerstraße", "Kaiserstraße"],
    "Hamburg": ["Mönckebergstraße", "Jungfernstieg", "Reeperbahn"],
    "Cologne": ["Schildergasse", "Hohe Straße", "Ehrenstraße"],
    "Stuttgart": ["Königstraße", "Calwer Straße", "Wilhelmsplatz"],
    "Düsseldorf": ["Königsallee", "Schadowstraße", "Flinger Straße"],
    "Dortmund": ["Westenhellweg", "Kleppingstraße", "Ostenhellweg"],
    "Essen": ["Kettwiger Straße", "Limbecker Platz", "Rüttenscheider Straße"],
    "Leipzig": ["Grimmaische Straße", "Nikolaistraße", "Karl-Liebknecht-Straße"],
    "Rome": ["Via del Corso", "Via Condotti", "Via Veneto"],
    "Milan": ["Corso Vittorio Emanuele II", "Via Montenapoleone", "Corso Buenos Aires"],
    "Naples": ["Spaccanapoli", "Via Toledo", "Via dei Tribunali"],
    "Turin": ["Via Roma", "Corso San Maurizio", "Via Po"],
    "Palermo": ["Via Vittorio Emanuele", "Corso Vittorio Emanuele", "Via Maqueda"],
    "Genoa": ["Via XX Settembre", "Via Garibaldi", "Via San Lorenzo"],
    "Bologna": ["Via dell'Indipendenza", "Via Ugo Bassi", "Via Rizzoli"],
    "Florence": ["Via de' Tornabuoni", "Piazza della Repubblica", "Via della Vigna Nuova"],
    "Bari": ["Via Sparano", "Corso Cavour", "Corso Vittorio Emanuele II"],
    "Catania": ["Via Etnea", "Via Crociferi", "Via Garibaldi"],
    "Dublin": ["Grafton Street", "O'Connell Street", "Henry Street"],
    "Cork": ["Patrick Street", "Oliver Plunkett Street", "Grand Parade"],
    "Limerick": ["O'Connell Street", "William Street", "Henry Street"],
    "Galway": ["Shop Street", "Eyre Square", "Dominick Street Lower"],
    "Waterford": ["The Quay", "Barronstrand Street", "O'Connell Street"]
}

# Generar direcciones para las ciudades
for city, streets in streets_by_city.items():
    for street in streets:
        for number in range(1, 101):
            address = f"{street}, {number}"
            addresses[address] = city

In [10]:
city_to_province = {
    "Jerez de la Frontera": "Cádiz",
    "Madrid": "Madrid",
    "Barcelona": "Barcelona",
    "Seville": "Seville",
    "Valencia": "Valencia",
    "Bilbao": "Biscay",
    "Malaga": "Malaga",
    "Zaragoza": "Zaragoza",
    "Murcia": "Murcia",
    "Palma": "Balearic Islands",
    "Paris": "Île-de-France",
    "Marseille": "Bouches-du-Rhône",
    "Lyon": "Auvergne-Rhône-Alpes",
    "Toulouse": "Occitanie",
    "Nice": "Provence-Alpes-Côte d'Azur",
    "Nantes": "Loire-Atlantique",
    "Strasbourg": "Bas-Rhin",
    "Montpellier": "Hérault",
    "Bordeaux": "Gironde",
    "Lille": "Nord",
    "London": "Greater London",
    "Manchester": "Greater Manchester",
    "Liverpool": "Merseyside",
    "Edinburgh": "City of Edinburgh",
    "Glasgow": "Glasgow City",
    "Birmingham": "West Midlands",
    "Leeds": "West Yorkshire",
    "Bristol": "Bristol",
    "Sheffield": "South Yorkshire",
    "Leicester": "Leicestershire",
    "Berlin": "Berlin",
    "Munich": "Bavaria",
    "Frankfurt": "Hesse",
    "Hamburg": "Hamburg",
    "Cologne": "North Rhine-Westphalia",
    "Stuttgart": "Baden-Württemberg",
    "Düsseldorf": "North Rhine-Westphalia",
    "Dortmund": "North Rhine-Westphalia",
    "Essen": "North Rhine-Westphalia",
    "Leipzig": "Saxony",
    "Rome": "Lazio",
    "Milan": "Lombardy",
    "Naples": "Campania",
    "Turin": "Piedmont",
    "Palermo": "Sicily",
    "Genoa": "Liguria",
    "Bologna": "Emilia-Romagna",
    "Florence": "Tuscany",
    "Bari": "Apulia",
    "Catania": "Sicily",
    "Dublin": "Dublin",
    "Cork": "Cork",
    "Limerick": "Limerick",
    "Galway": "Galway",
    "Waterford": "Waterford"
}

In [11]:
def remove_short_last_word(input_str):
    words = input_str.split()
    if words:
        last_word = words[-1]
        if len(last_word) <= 3:
            words.pop()
        return ' '.join(words)
    else:
        return input_str

In [12]:
# Función para generar ID de proveedor
def generate_provider_id(company_name, country):
    company_name = remove_short_last_word(company_name)
    # Obtener las iniciales del nombre de la compañía
    words = company_name.split()
    if len(words) >= 3:
        initials = words[0][0] + words[1][0] + words[2][0]
    elif len(words) == 2:
        initials = words[0][:2] + words[1][0]
    elif len(words) == 1:
        initials = words[0][:3]
    else:
        # En caso de que no haya palabras en el nombre
        initials = "XXX"

    # Generar los 3 números aleatorios
    random_digits = ''.join(random.choice('0123456789') for _ in range(3))

    # Mapear el código del país
    country_codes = {
        'Spain': 'SP',
        'France': 'FR',
        'Germany': 'GE',
        'Ireland': 'IR',
        'United Kingdom': 'UK',
        'Italy': 'IT',
    }
    country_code = country_codes.get(country, 'XX')  # 'XX' para países desconocidos

    # Combinar las partes para formar el ID de proveedor
    provider_id = f'prov{initials}{random_digits}{country_code}'

    return provider_id

In [13]:
def assign_location(row):
    country = row['country']
    city = random.choice([c for c, c_country in cities.items() if c_country == country])
    address = random.choice([a for a, a_city in addresses.items() if a_city == city])
    province = city_to_province.get(city, 'Sin Provincia')
    return pd.Series([address, city, province])

In [14]:
df = name_comp.copy()
df['ID_proveedor'] = df.apply(lambda row: generate_provider_id(row['company_name'], row['country']), axis=1)
df['Nombre'] = df['company_name']
df[['Dirección', 'Ciudad', 'Provincia']] = df.apply(assign_location, axis=1)
df = df.drop(['company_name', 'country'], axis=1)
df

,ID_proveedor,Nombre,Dirección,Ciudad,Provincia
0,provLMH411FR,"LVMH Moët Hennessy - Louis Vuitton, SE","Place Royale, 62",Nantes,Loire-Atlantique
1,provL'O121FR,L'Oréal SA,"Avenue de l'Opéra, 19",Paris,Île-de-France
2,provHeI379FR,Hermès International SCA,"Rue Sainte-Catherine, 75",Bordeaux,Gironde
3,provChD276FR,Christian Dior SE,"Rue Sainte-Catherine, 53",Bordeaux,Gironde
4,provTot737FR,TotalEnergies SE,"Place Royale, 51",Nantes,Loire-Atlantique
...,...,...,...,...,...
1053,provBOI557IR,Bank Of Ireland (Governor & Company Of The),"Eyre Square, 80",Galway,Galway
1054,provApp240IR,Applegreen plc,"O'Connell Street, 19",Waterford,Waterford
1055,provMal000IR,Mallinckrodt plc,"Henry Street, 4",Limerick,Limerick
1056,provGaG830IR,Gambling.com Group Ltd,"Grand Parade, 96",Cork,Cork
1057,provAbb273IR,Abbey plc,"Grafton Street, 74",Dublin,Dublin

In [17]:
# df_prov = df.copy()

# Aquí viene la tabla de pedidos

In [123]:
def generate_combinations(n, m):
    numbers = [str(num) for num in range(10)]  # Convertir números a cadenas
    letters = string.ascii_letters  # Obtener letras

    number_combinations = combinations(numbers, n)
    letter_combinations = combinations(letters, m)

    result = []
    for num_comb in number_combinations:
        for let_comb in letter_combinations:
            combined = ''.join(num_comb) + ''.join(let_comb)
            result.append(combined)
    
    return result

In [131]:
def generar_id_pedidos(num_elementos):
    
    combinations = generate_combinations(5, 6)

    unique_samples = random.sample(combinations, num_elementos)
    lista_id_pedidos = ['pedi' + sample for sample in unique_samples]

    return lista_id_pedidos

In [16]:
def check_repetition(lst, num_elementos, target_element, per = 0.45):
    threshold = num_elementos * per
    count = 0
    
    for item in lst:
        if item == target_element:
            count += 1
            if count > threshold:
                return True
    
    return False

In [17]:
def selec_prov_aleatorio_v2(num_elementos, df = df):
    # Número de proveedores diferentes
    n_prov = int(math.sqrt(num_elementos)) + 1
        
    # Obtener la lista de ID de proveedores
    id_proveedores = df['ID_proveedor'].tolist()
    
    # Realizar la selección
    if len(id_proveedores) <= n_prov:
        lista_seleccionada = id_proveedores
    else:
        lista_seleccionada = random.sample(id_proveedores, n_prov)
    
    # Declaramos la lista prov_selec
    prov_selec = []

    # Calcular la cantidad de repeticiones y añadir los elementos a la lista
    prov_selec.extend(lista_seleccionada)
    while len(prov_selec) < num_elementos:
        sel_random = random.choice(lista_seleccionada)
        if check_repetition(prov_selec, num_elementos, sel_random):
            id_proveedores.remove(sel_random)
            continue
        n_random = random.randint(1,int(math.sqrt(num_elementos - len(prov_selec))))
        if len(prov_selec) + n_random > num_elementos:          # Esta comrobación es un poco inutil ya que con la raiz cuadrada siempre se va cumplir. 
            continue
        for i in range(n_random):
            prov_selec.append(sel_random)
    
    return prov_selec

In [18]:
def generar_fechas_aleatorias(num_elementos, num_meses = 24):
    # Obtener la fecha actual
    fecha_actual = datetime.now()

    # Calcular la fecha de inicio como 'num_meses' meses atrás
    fecha_inicio = fecha_actual - timedelta(days=num_meses * 30)

    # Generar fechas aleatorias dentro del rango especificado
    fechas_aleatorias = []
    for _ in range(num_elementos):
        # Calcular un número aleatorio de días entre 0 y 'num_meses * 30'
        dias_aleatorios = random.randint(0, num_meses * 30)

        # Calcular la fecha aleatoria dentro del rango
        fecha_aleatoria = fecha_inicio + timedelta(days=dias_aleatorios)

        # Formatear la fecha en "día mes año" y agregarla a la lista
        fecha_formateada = fecha_aleatoria.strftime("%d %m %Y")
        fechas_aleatorias.append(fecha_formateada)

    return fechas_aleatorias

In [19]:
def generar_df_pedidos(num_filas, num_meses = 15):
    id_ped = generar_id_pedidos(num_filas)
    id_prov = selec_prov_aleatorio_v2(num_filas)
    date = generar_fechas_aleatorias(num_filas, num_meses)

    df_ped = pd.DataFrame({'ID_pedido': id_ped, 'ID_proveedor': id_prov, 'Fecha': date})

    df_ped['Fecha'] = pd.to_datetime(df_ped['Fecha'], format='%d %m %Y')
    df_ped.sort_values('Fecha', inplace=True, ascending= False)
    df_ped = df_ped.reset_index(drop = True)
    df_ped['Fecha'] = df_ped['Fecha'].dt.strftime("%d/%m/%Y")
    return df_ped

In [23]:
# df_ped = generar_df_pedidos(10)
# df_ped.info()
# df_ped

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   ID_pedido     10 non-null     object
 1   ID_proveedor  10 non-null     object
 2   Fecha         10 non-null     object
dtypes: object(3)
memory usage: 372.0+ bytes

          ID_pedido  ID_proveedor       Fecha
0  pedi059321ZECUDN  provHap551GE  12/11/2023
1  pedi944743LAWORC  provWPP585UK  10/11/2023
2  pedi414428DRVTPE  provHap551GE  18/10/2023
3  pedi378700OQBJHN  provHap551GE  04/06/2023
4  pedi689909XPUDFX  provTec197FR  26/03/2023
5  pedi157132ZPSGXZ  provDiS888IT  20/03/2023
6  pedi358151MHNYEF  provTec197FR  05/03/2023
7  pedi508800CFOUPY  provTec197FR  28/02/2023
8  pedi810064SEHUGD  provTec197FR  23/01/2023
9  pedi581693WXLVLX  provDiS888IT  23/09/2022

In [20]:
def adjust_weights_parabola(current_value, start_weights = [20, 35, 20, 9, 15, 1], end_weights = [1, 1, 1, 2, 5, 90], end_value = 365, start_value = 1):
    """
    Adjust the weights based on the current value, following the descending part of a parabolic curve.
    
    :param start_weights: List of weights at the start value.
    :param end_weights: List of weights at the end value.
    :param current_value: The current value based on which weights need to be adjusted.
    :param start_value: The value at which the weights are start_weights.
    :param end_value: The value at which the weights are end_weights.
    :return: Adjusted list of weights.
    """
    # Calculate the ratio of interpolation
    ratio = (current_value - start_value) / (end_value - start_value)

    # Interpolate the weights
    interpolated_weights = np.array(start_weights) * (1 - ratio) + np.array(end_weights) * ratio

    # Normalize the weights to sum up to 100
    normalized_weights = 100 * interpolated_weights / sum(interpolated_weights)
    
    return normalized_weights.tolist()

In [21]:
def asignar_estado(fecha, estados):
    fecha_actual = datetime.now()
    date = pd.to_datetime(fecha, format = '%d/%m/%Y')
    dias_diferencia = (fecha_actual - date).days

    if dias_diferencia <= 1:
        return estados[0]
    elif dias_diferencia > 400: 
        porcentajes = [1,1,1,1,2,94]
        return random.choices(estados, porcentajes)
    else:
        return random.choices(estados, adjust_weights_parabola(dias_diferencia))

In [88]:
def asignar_estados_df(df, estados=['Por hacer', 'Pagado', 'De Camino', 'Recibido', 'Almacenado', 'Distribuido']): 
    df['Estado'] = df['Fecha'].apply(asignar_estado, estados=estados)
    return df

In [27]:
# asignar_estados_df()

          ID_pedido  ID_proveedor       Fecha Estado_asignado
0  pedi059321ZECUDN  provHap551GE  12/11/2023     [Por hacer]
1  pedi944743LAWORC  provWPP585UK  10/11/2023    [Almacenado]
2  pedi414428DRVTPE  provHap551GE  18/10/2023   [Distribuido]
3  pedi378700OQBJHN  provHap551GE  04/06/2023   [Distribuido]
4  pedi689909XPUDFX  provTec197FR  26/03/2023   [Distribuido]
5  pedi157132ZPSGXZ  provDiS888IT  20/03/2023   [Distribuido]
6  pedi358151MHNYEF  provTec197FR  05/03/2023   [Distribuido]
7  pedi508800CFOUPY  provTec197FR  28/02/2023      [Recibido]
8  pedi810064SEHUGD  provTec197FR  23/01/2023     [Por hacer]
9  pedi581693WXLVLX  provDiS888IT  23/09/2022   [Distribuido]

# Aquí va Categorías

In [24]:
nombre_categorias = ['Mercería', 'Herramientas', 'Construcción', 'Cosmética', 'Mobiliario', 'Alimentación', 'Informática']

In [25]:
# Función para generar ID de categoría
def generate_category_id(category):
    category_name = remove_short_last_word(category)
    # Obtener las iniciales del nombre de la categoría
    words = category.split()
    if len(words) >= 3:
        initials = words[0][:2] + words[1][0] + words[2][0]
    elif len(words) == 2:
        initials = words[0][:2] + words[1][:2]
    elif len(words) == 1:
        initials = words[0][:4]
    else:
        # En caso de que no haya palabras en el nombre
        initials = "XXX"

    # Generar los 3 números aleatorios
    random_digits = ''.join(random.choice('0123456789') for _ in range(3))

    # Combinar las partes para formar el ID de proveedor
    provider_id = f'cate{initials}{random_digits}'

    return provider_id

In [26]:
def generar_df_cate():
    df_cate = pd.DataFrame({'Nombre': nombre_categorias})
    df_cate['ID_categoría'] = df_cate['Nombre'].apply(generate_category_id)
    return df_cate

In [31]:
# df_cate = generar_df_cate()

# Aquí va Piezas

In [27]:
categorias_dict = {
    'Mercería': ['Hilos', 'Agujas', 'Botones', 'Cintas', 'Encajes', 'Cremalleras', 'Cinturones', 'Tijeras', 'Telas', 'Pegamento'],
    'Herramientas': ['Martillos', 'Destornilladores', 'Sierras', 'Llaves', 'Pinzas', 'Cintas métricas', 'Taladros', 'Cinceles', 'Niveles', 'Lijadoras'],
    'Construcción': ['Ladrillos', 'Cemento', 'Listón de madera', 'Pintura', 'Herramientas de construcción', 'Yeso', 'Azulejos', 'Cables eléctricos', 'Tubos de PVC', 'Clavos'],
    'Cosmética': ['Maquillaje', 'Cremas', 'Perfumes', 'Pintalabios', 'Champú', 'Esmaltes de uñas', 'Brochas de maquillaje', 'Aceites esenciales', 'Mascarillas faciales', 'Lociones corporales'],
    'Mobiliario': ['Sofás', 'Mesas', 'Sillas', 'Armarios', 'Camas', 'Estanterías', 'Escritorios', 'Lámparas', 'Mesitas de noche', 'Sillones'],
    'Alimentación': ['Frutas', 'Verduras', 'Carnes', 'Pescados', 'Productos enlatados', 'Lácteos', 'Pan fresco', 'Bebidas', 'Snacks', 'Dulces'],
    'Informática': ['Portátiles', 'Impresoras', 'Gafas RV', 'PCs', 'Componentes', 'Monitores', 'Teclados', 'Ratones', 'Auriculares', 'Cables'],
}

In [ ]:
nombre_piezas = [valor for valores in categorias_dict.values() for valor in valores for _ in range(10)]
c = ['Rojo', 'Azul', 'Amarillo', 'Verde', 'Naranja', 'Morado', 'Negro', 'Blanco', 'Rosa', 'Marrón']
colores = [color for color in c * 70]
# nombre_piezas

In [100]:
precios_orientativos = {
    'Mercería': [random.uniform(1.0, 10.0) for _ in range(10)],
    'Herramientas': [random.uniform(5.0, 50.0) for _ in range(10)],
    'Construcción': [random.uniform(10.0, 100.0) for _ in range(10)],
    'Cosmética': [random.uniform(2.0, 20.0) for _ in range(10)],
    'Mobiliario': [random.uniform(50.0, 500.0) for _ in range(10)],
    'Alimentación': [random.uniform(0.5, 5.0) for _ in range(10)],
    'Informática': [random.uniform(20.0, 200.0) for _ in range(10)],
}
lista_precios_orientativos = [f'{str(round(precio,2)).replace(".", ",")} €' for precios in precios_orientativos.values() for precio in precios for _ in range(10)]
len(lista_precios_orientativos)

700

In [96]:
precio = 2.3
f'{str(precio).replace(".", ",")}'

'2,3'

In [30]:
def encontrar_categoria(nombre_pieza, diccionario=categorias_dict):
    for categoria, productos in diccionario.items():
        if nombre_pieza in productos:
            return categoria
    return None

In [31]:
def encontrar_id_categoria(row, diccionario):
    nombre_pieza = row['Nombre']
    categoria = encontrar_categoria(nombre_pieza, diccionario)
    if categoria:
        return categoria
    return None

In [32]:
# Función para generar ID de pieza
def generate_pieza_id(pieza, categoria, color):
    # Obtener las iniciales del nombre de la pieza
    words = pieza.split()
    if len(words) >= 3:
        initials = words[0][0] + words[1][0] + words[2][0]
    elif len(words) == 2:
        initials = words[0][:2] + words[1][0]
    elif len(words) == 1:
        initials = words[0][:3]
    else:
        # En caso de que no haya palabras en el nombre
        initials = "XXX"

    # Obtener las iniciales del nombre de la categoría
    word_cate = categoria.split()
    if len(word_cate) >= 3:
        inic = word_cate[0][0] + word_cate[1][0] + word_cate[2][0]
    elif len(word_cate) == 2:
        inic = word_cate[0][:2] + word_cate[1][0]
    elif len(word_cate) == 1:
        inic = word_cate[0][:3]
    else:
        # En caso de que no haya palabras en el nombre
        inic = "XXX"

    # Generar los 3 números aleatorios
    random_digits = ''.join(random.choice('0123456789') for _ in range(3))

    # Mapear el código del país
    color_codes = {
        'Rojo': 'Rj',
        'Azul': 'Az',
        'Verde': 'Ve',
        'Amarillo': 'Am',
        'Negro': 'Ng',
        'Blanco': 'Bl',
        'Morado': 'Mo',
        'Naranja': 'Na',
        'Rosa': 'Rs',
        'Marrón': 'Mr'
    }
    color_code = color_codes.get(color, 'XX')  # 'XX' para países desconocidos

    # Combinar las partes para formar el ID de proveedor
    provider_id = f'piez{initials}{random_digits}{color_code}{inic}'

    return provider_id

In [103]:
def generar_df_pieza(df_cate):

    df_piez = pd.DataFrame({'Nombre': nombre_piezas, 'Color': colores, 'Precio': [num for num in lista_precios_orientativos]})

    df_piez['ID_pieza'] = df_piez.apply(lambda row: generate_pieza_id(row['Nombre'], encontrar_id_categoria(row, categorias_dict), row['Color']), axis=1)

    df_piez['Nombre_categoría'] = df_piez['Nombre'].apply(encontrar_categoria)
    
    # Crear un diccionario que mapee nombre de categoría a ID de categoría
    categoria_id_mapping = df_cate.set_index('Nombre')['ID_categoría'].to_dict()
    # Agregar la columna "ID_categoría" en df_piez basada en el mapeo de nombres de categoría a ID
    df_piez['ID_categoría'] = df_piez['Nombre_categoría'].map(categoria_id_mapping)

    df_piez.drop('Nombre_categoría', axis = 1, inplace= True)
    columnas = df_piez.columns.tolist()
    columnas.insert(0, columnas.pop(columnas.index("ID_pieza")))
    df_piez = df_piez[columnas]

    # df_piez['ID_Categoria'] = df_piez.apply(lambda row: encontrar_id_categoria(row, categorias_dict), axis=1)  

    return df_piez

In [39]:
# df_piez = generar_df_pieza()

In [ ]:
# df_piez

# Aquí va Detalles

In [41]:
def lista_idpedido_aleatorio(num_elementos, df):
   
    # Obtener la lista de ID de proveedores
    id_pedidos = df['ID_pedido'].tolist()
    
    # Declaramos la lista ped_selec
    ped_selec = []

    # Calcular la cantidad de repeticiones y añadir los elementos a la lista
    ped_selec.extend(id_pedidos)
    while len(ped_selec) < num_elementos:
        sel_random = random.choice(id_pedidos)
        if check_repetition(ped_selec, num_elementos, sel_random, per = (40/(num_elementos+1))):
            id_pedidos.remove(sel_random)
            continue
        n_random = random.randint(1,int(math.sqrt(num_elementos - len(ped_selec))))
        if len(ped_selec) + n_random > num_elementos:          # Esta comrobación es un poco inutil ya que con la raiz cuadrada siempre se va cumplir. 
            continue
        for i in range(n_random):
            ped_selec.append(sel_random)
    
    return ped_selec

In [84]:
def generar_df_detalles(num_elementos, df_pe, df_pi):

    df_deta = pd.DataFrame({'ID_pieza': [random.choice(df_pi['ID_pieza']) for _ in range(num_elementos)]})

    df_deta['ID_pedido'] = lista_idpedido_aleatorio(num_elementos, df_pe)

    df_deta['Cantidad'] = [random.randint(1,10) for _ in range(num_elementos)]

    return df_deta

In [43]:
# df_deta = generar_df_detalles(len(df_ped)*4)

In [85]:
def generar_todo(numero_filas):
    global df
    df_ped = generar_df_pedidos(numero_filas)
    asignar_estados_df(df_ped)
    df_prov = df[df['ID_proveedor'].isin(df_ped['ID_proveedor'].unique())]
    df_prov = df_prov.reset_index(drop = True)
    df_cate = generar_df_cate()
    df_piez = generar_df_pieza(df_cate)
    df_deta = generar_df_detalles(len(df_ped)*4, df_ped, df_piez)

    return [df_prov, df_ped, df_deta, df_piez, df_cate]

In [134]:
dataset = generar_todo(1000000)
df_prov = dataset[0]
df_ped = dataset[1] 
df_deta = dataset[2]
df_piez = dataset[3]
df_cate = dataset[4]

a = len(df_ped)

df_prov.to_csv(f'proveedores_{a}.csv', index=False)
df_ped.to_csv(f'pedidos_{a}.csv', index=False)
df_piez.to_csv(f'piezas_{a}.csv', index=False)
df_cate.to_csv(f'categorias_{a}.csv', index=False)
df_deta.to_csv(f'detalles_{a}.csv', index=False)

In [108]:
tabla_proveedores = pd.read_csv('proveedores_10.csv')
tabla_pedidos = pd.read_csv('pedidos_10.csv')
tabla_piezas = pd.read_csv('piezas_10.csv')
tabla_categoria = pd.read_csv('categorias_10.csv')
tabla_detalles = pd.read_csv('detalles_10.csv')

display(tabla_proveedores)
display(tabla_pedidos)
display(tabla_piezas)
display(tabla_categoria)
display(tabla_detalles)

,ID_proveedor,Nombre,Dirección,Ciudad,Provincia
0,provBNP829FR,BNP Paribas SA,"Rue Saint-Ferréol, 31",Marseille,Bouches-du-Rhône
1,provAka495GE,Akasol AG,"Reeperbahn, 86",Hamburg,Hamburg
2,provTBB562UK,Tritax Big Box REIT plc,"George Street, 75",Edinburgh,City of Edinburgh
3,provPrS439IT,Prysmian S.p.A.,"Via Maqueda, 33",Palermo,Sicily

          ID_pedido  ID_proveedor       Fecha           Estado
0  pedi835935KUQHTG  provBNP829FR  31/10/2023       ['Pagado']
1  pedi062355COKKJZ  provBNP829FR  14/09/2023  ['Distribuido']
2  pedi991512CEFFKQ  provAka495GE  12/09/2023   ['Almacenado']
3  pedi078656LVFYWO  provTBB562UK  07/07/2023   ['Almacenado']
4  pedi230218GJMBYO  provAka495GE  06/07/2023  ['Distribuido']
5  pedi374632UGUYKC  provPrS439IT  17/06/2023   ['Almacenado']
6  pedi173150SQKHJF  provTBB562UK  13/04/2023    ['Por hacer']
7  pedi035898NSFLPT  provBNP829FR  12/04/2023    ['Por hacer']
8  pedi651213FNTZCH  provAka495GE  08/04/2023    ['Por hacer']
9  pedi491807WSRENF  provPrS439IT  03/03/2023  ['Distribuido']

            ID_pieza  Nombre     Color    Precio ID_categoría
0    piezHil424RjMer   Hilos      Rojo     5,7 €  cateMerc333
1    piezHil354AzMer   Hilos      Azul     5,7 €  cateMerc333
2    piezHil365AmMer   Hilos  Amarillo     5,7 €  cateMerc333
3    piezHil639VeMer   Hilos     Verde     5,7 €  cateMerc333
4    piezHil886NaMer   Hilos   Naranja     5,7 €  cateMerc333
..               ...     ...       ...       ...          ...
695  piezCab888MoInf  Cables    Morado  193,71 €  cateInfo684
696  piezCab641NgInf  Cables     Negro  193,71 €  cateInfo684
697  piezCab890BlInf  Cables    Blanco  193,71 €  cateInfo684
698  piezCab322RsInf  Cables      Rosa  193,71 €  cateInfo684
699  piezCab674MrInf  Cables    Marrón  193,71 €  cateInfo684

[700 rows x 5 columns]

         Nombre ID_categoría
0      Mercería  cateMerc333
1  Herramientas  cateHerr775
2  Construcción  cateCons806
3     Cosmética  cateCosm990
4    Mobiliario  cateMobi809
5  Alimentación  cateAlim456
6   Informática  cateInfo684

           ID_pieza         ID_pedido  Cantidad
0   piezAur990RsInf  pedi835935KUQHTG         6
1   piezPin281RjHer  pedi062355COKKJZ         1
2   piezArm283MoMob  pedi991512CEFFKQ         3
3   piezDes500NgHer  pedi078656LVFYWO         4
4   piezPre435RsAli  pedi230218GJMBYO         4
5   piezImp712MoInf  pedi374632UGUYKC         2
6   piezPer181RsCos  pedi173150SQKHJF         7
7   piezMaq620RsCos  pedi035898NSFLPT         5
8   piezEst268BlMob  pedi651213FNTZCH         1
9   piezCem180RjCon  pedi491807WSRENF        10
10  piezHdc083BlCon  pedi491807WSRENF         5
11  piezMaf145RsCos  pedi491807WSRENF         7
12  piezBot174BlMer  pedi491807WSRENF         7
13  piezEnc824NaMer  pedi491807WSRENF         1
14  piezMaf548NgCos  pedi078656LVFYWO         7
15  piezEnc858BlMer  pedi078656LVFYWO         1
16  piezPCs740RjInf  pedi078656LVFYWO         7
17  piezAce290AzCos  pedi078656LVFYWO         2
18  piezSna832MrAli  pedi991512CEFFKQ         9
19  piezBdm146MrCos  pedi991512CEFFKQ         4
20  piezLoc774MoCos  pedi991512CEFFKQ         5
21  piezYes214BlCon  pedi991512CEFFKQ         6
22  piezDes921AmHer  pedi035898NSFLPT         8
23  piezGaR681MoInf  pedi230218GJMBYO         5
24  piezGaR441AzInf  pedi230218GJMBYO         5
25  piezEnc534MrMer  pedi230218GJMBYO         2
26  piezMdn248MrMob  pedi230218GJMBYO         5
27  piezCin707NaMer  pedi173150SQKHJF         8
28  piezCab140AmInf  pedi173150SQKHJF         7
29  piezTel602BlMer  pedi491807WSRENF         7
30  piezPer341MrCos  pedi491807WSRENF         2
31  piezLij570AzHer  pedi491807WSRENF         9
32  piezEdu565MoCos  pedi491807WSRENF         8
33  piezCam523MoMob  pedi491807WSRENF         7
34  piezPCs751AmInf  pedi173150SQKHJF         9
35  piezCab692RjInf  pedi173150SQKHJF         4
36  piezLoc174RjCos  pedi835935KUQHTG         4
37  piezPes928AmAli  pedi835935KUQHTG         6
38  piezVer054AmAli  pedi078656LVFYWO         1
39  piezLác463RsAli  pedi651213FNTZCH         1